include:
  - package:flutter_lints/flutter.yaml
  # - package:very_good_analysis/analysis_options.yaml

analyzer:
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false

  # error || warning || ignore
  # errors:
    # invalid_assignment: error
    # document_ignores: ignore
    # inference_failure_on_function_invocation: ignore
    # inference_failure_on_instance_creation: ignore
    # strict_raw_type: ignore
    # use_setters_to_change_properties: ignore
    # lines_longer_than_80_chars: ignore
    # non_bool_negation_expression: ignore
    # avoid_slow_async_io: ignore
    # prefer_constructors_over_static_methods: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # avoid_redundant_argument_values: true
    # close_sinks: true
    prefer_final_fields: true
    prefer_final_locals: true
    # public_member_api_docs: false
    # avoid_catches_without_on_clauses: false
    # avoid_dynamic_calls: false
    # avoid_annotating_with_dynamic: false
    # always_use_package_imports: false
