name: flavorizr
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  awesome_dio_interceptor: ^1.3.0
  cloud_firestore: ^6.0.1
  connectivity_plus: ^7.0.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  dio: ^5.9.0
  firebase_analytics: ^12.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_messaging: ^16.0.1
  firebase_remote_config: ^6.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  sentry: ^9.6.0
  shared_preferences: ^2.5.3
  stack_trace: ^1.12.1
  talker_dio_logger: ^5.0.0
  talker_flutter: ^5.0.0
  worker_manager: ^7.2.6

dev_dependencies:
  flutter_flavorizr: ^2.4.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
      bundleId: com.example.flavorizr
  flavors:
    dev:
      app:
        name: "Flavorizr Dev"
      android:
        applicationId: "com.example.flavorizr.dev"
        resValues:
          app_name:
            type: "string"
            value: "Flavorizr Dev"
      ios:
        bundleId: "com.example.flavorizr.dev"
        buildSettings:
          PRODUCT_BUNDLE_IDENTIFIER: "com.example.flavorizr.dev"
    staging:
      app:
        name: "Flavorizr Staging"
      android:
        applicationId: "com.example.flavorizr.staging"
        resValues:
          app_name:
            type: "string"
            value: "Flavorizr Staging"
      ios:
        bundleId: "com.example.flavorizr.staging"
        buildSettings:
          PRODUCT_BUNDLE_IDENTIFIER: "com.example.flavorizr.staging"
    prod:
      app:
        name: "Flavorizr"
      android:
        applicationId: "com.example.flavorizr"
        resValues:
          app_name:
            type: "string"
            value: "Flavorizr"
      ios:
        bundleId: "com.example.flavorizr"
        buildSettings:
          PRODUCT_BUNDLE_IDENTIFIER: "com.example.flavorizr"
