// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLc1y9h4O0K-aUEBZRFMHgNdfe2kdTJJU',
    appId: '1:680114093491:web:ed0d703ced3f945b5b5fc6',
    messagingSenderId: '680114093491',
    projectId: 'flavorizr-b3322-staging',
    authDomain: 'flavorizr-b3322-staging.firebaseapp.com',
    storageBucket: 'flavorizr-b3322-staging.firebasestorage.app',
    measurementId: 'G-N71ER7C874',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdxOI-zdIODk-zQoENkMxp1D2rMA-SxSI',
    appId: '1:680114093491:android:548fe36d78f8bf005b5fc6',
    messagingSenderId: '680114093491',
    projectId: 'flavorizr-b3322-staging',
    storageBucket: 'flavorizr-b3322-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnG0vHCPp1vqz1Uk76FTuKTjCSSkLkJ1c',
    appId: '1:680114093491:ios:97f682b9aceeae165b5fc6',
    messagingSenderId: '680114093491',
    projectId: 'flavorizr-b3322-staging',
    storageBucket: 'flavorizr-b3322-staging.firebasestorage.app',
    iosBundleId: 'com.example.flavorizr.staging',
  );
}
