// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzVyW6zCQd7GUQeBRIcCxZPeQKavwZav4',
    appId: '1:695921448768:web:f12c9269d7067ae7600ca5',
    messagingSenderId: '695921448768',
    projectId: 'flavorizr-b3322',
    authDomain: 'flavorizr-b3322.firebaseapp.com',
    storageBucket: 'flavorizr-b3322.firebasestorage.app',
    measurementId: 'G-QTB2WL7QXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3yIMVu3Oo5J_Wo-oz4c_DX8hgfSeSnWg',
    appId: '1:695921448768:android:6fc06c5817e8bba0600ca5',
    messagingSenderId: '695921448768',
    projectId: 'flavorizr-b3322',
    storageBucket: 'flavorizr-b3322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXIgHxckwLTE1tgQFqJRygwWPxLgXHYiA',
    appId: '1:695921448768:ios:83ade3c5c165f6a8600ca5',
    messagingSenderId: '695921448768',
    projectId: 'flavorizr-b3322',
    storageBucket: 'flavorizr-b3322.firebasestorage.app',
    iosBundleId: 'com.example.flavorizr',
  );
}
