// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPvd7NimCLY2-XRS26iVBkV_tgupsRmxg',
    appId: '1:190409895766:web:413c3fd598b49b90a830f7',
    messagingSenderId: '190409895766',
    projectId: 'flavorizr-b3322-dev',
    authDomain: 'flavorizr-b3322-dev.firebaseapp.com',
    storageBucket: 'flavorizr-b3322-dev.firebasestorage.app',
    measurementId: 'G-NVRNFYS6EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6txMzGUbIOR08BlGlGLMZNWaIga6Z1g',
    appId: '1:190409895766:android:499d8dbe2ad68140a830f7',
    messagingSenderId: '190409895766',
    projectId: 'flavorizr-b3322-dev',
    storageBucket: 'flavorizr-b3322-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwMTMQxqjr_tgbTX30MH6kmBzC_OIsjEI',
    appId: '1:190409895766:ios:49f9dc22b240fc04a830f7',
    messagingSenderId: '190409895766',
    projectId: 'flavorizr-b3322-dev',
    storageBucket: 'flavorizr-b3322-dev.firebasestorage.app',
    iosBundleId: 'com.example.flavorizr.dev',
  );
}
